// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { add } from "./add.js";
import { addAll } from "./addAll.js";
import { clone } from "./clone.js";
import { compact } from "./compact.js";
import { create } from "./create.js";
import { difference } from "./difference.js";
import { forEach } from "./forEach.js";
import { has } from "./has.js";
import { hasAll } from "./hasAll.js";
import { hasAny } from "./hasAny.js";
import { hasNone } from "./hasNone.js";
import { intersection } from "./intersection.js";
import { is } from "./is.js";
import { isDisjointFrom } from "./isDisjointFrom.js";
import { isEmpty } from "./isEmpty.js";
import { isShallowEqual } from "./isShallowEqual.js";
import { isSubsetOf } from "./isSubsetOf.js";
import { isSupersetOf } from "./isSupersetOf.js";
import { mapEach } from "./mapEach.js";
import { remove } from "./remove.js";
import { removeAll } from "./removeAll.js";
import { size } from "./size.js";
import { symmetricDifference } from "./symmetricDifference.js";
import { toArray } from "./toArray.js";
import { union } from "./union.js";

declare namespace Set {
    export {
        add,
        addAll,
        clone,
        compact,
        create,
        difference,
        forEach,
        has,
        hasAll,
        hasAny,
        hasNone,
        intersection,
        is,
        isDisjointFrom,
        isEmpty,
        isShallowEqual,
        isSubsetOf,
        isSupersetOf,
        mapEach,
        remove,
        removeAll,
        size,
        symmetricDifference,
        toArray,
        union,
    }
}

export {
    Set,
}
